### ISSUE TITLE
ImportError: [...] undefined symbol: PyClass_Type, Boost related

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/PyBDSF#123]
Dear Authors,

I Installed latest master of PyBDSF Under Ubuntu 18:
```
export BOOST_VERSION=1.65

# Run-time dependencies
aptitude install -y libboost-python${BOOST_VERSION}.1 libboost-numpy${BOOST_VERSION}.1

# Install
export BUILD_PACKAGES="git g++ gfortran libboost-python${BOOST_VERSION}-dev libboost-numpy${BOOST_VERSION}-dev python3-setuptools python3-numpy-dev swig3.0"
aptitude install -y ${BUILD_PACKAGES}

pip3 install git+https://github.com/lofar-astron/PyBDSF.git

```

Those dependencies I take from:
https://svn.astron.nl/LOFAR/tags/LOFAR-Release-4_0_11/Docker/lofar-pipeline/Dockerfile.tmpl

When Im trying to run it, it says:

> Traceback (most recent call last):
>   File "/usr/local/bin/pybdsf", line 10, in <module>
>     import bdsf
>   File "/usr/local/lib/python3.6/dist-packages/bdsf/__init__.py", line 21, in <module>
>     from .collapse import Op_collapse
>   File "/usr/local/lib/python3.6/dist-packages/bdsf/collapse.py", line 11, in <module>
>     from . import _cbdsm
> ImportError: /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1: undefined symbol: PyClass_Type

**Comment by tammojan** [comment]
Somehow the installer linked to boost_python2.7 while you are running python 3.6. I think it should work better if you install boost-python36 (I think the Dockerfile you refer to has boost-python${PYTHON_VERSION} where PYTHON_VERSION is 36).

**Comment by AlexKurek** [comment]
PYTHON_VERSION  is set like this:
https://git.astron.nl/ro/lofar/-/blob/master/Docker/lofar-base/Dockerfile.tmpl#L53

`BOOST_VERSION=1.65`

And if I do:
`-name libboost_python-py*`
it gives:

> /usr/lib/x86_64-linux-gnu/libboost_python-py27.a
> /usr/lib/x86_64-linux-gnu/libboost_python-py27.so.1.65.1
> /usr/lib/x86_64-linux-gnu/libboost_python-py36.a
> /usr/lib/x86_64-linux-gnu/libboost_python-py27.so
> /usr/lib/x86_64-linux-gnu/libboost_python-py36.so

I think there is no `boost-python36` package

**Comment by tammojan** [comment]
Sorry I was confused about the boost version. I'm afraid you'll have to build your own boost python for python3 on Ubuntu 18.04, since there doesn't seem to be a package available for it.

**Comment by tammojan** [comment]
Alternatively, could you try installing the binary wheel with pip install pybdsf?

**Comment by AlexKurek** [comment]
At the same time LOFARsoft's cmake was able to find libbost for Python 3.6:
`Boost_PYTHON-PY36_LIBRARY_RELE   /usr/lib/x86_64-linux-gnu/libboost_python-py36.so` (from ccmake)
Would it mean that the required library in fact is present om Ubuntu 18?

**Comment by AlexKurek** [comment]
The latest master is not detected by LOFARSoft 3.2.18 (the latest from 3.x branch) any more. On the same "machine" (my own Dockerfile for Prefactor 3 and all dependencies) 1.9.2 is still detected. Is it expected?

**Comment by tammojan** [comment]
No, as far as I know there was no change in detecting bdsf in LofarSoft. Could you share your dockerfile in some way so I can debug?

**Comment by AlexKurek** [comment]
I just checked that commit 5f325b7842b2f129632f4cea35382891fc4b2260 is also OK.

It is attached. If you comment line 262 it should fal at the point where LOFARsoft is build.
[Dockerfile.zip](https://github.com/lofar-astron/PyBDSF/files/4349051/Dockerfile.zip)

**Comment by AlexKurek** [comment]
In Ubuntu 18 and for PyBDSF compiled using Python 2.7: Matplotlib is detected only if it was installed using apt-get. If it was installed using pip (pip2), it is not detected. This isssue is not present in PyBDSF@Python3.

Here is a Dockerfile for Ubuntu 18 (the previous one was for Ubuntu 16), if you want to verify it.

Best regards,
Alex

[Dockerfile.zip](https://github.com/lofar-astron/PyBDSF/files/4386673/Dockerfile.zip)

**Comment by AlexKurek** [comment]
It seems I solved this. `pip install matplotlib==1.5.1` is detected under Ubuntu 18 and Python 2. This is the version from Ubuntu 16. Newer versions of of matplotlib, e.g. 2.1.1 (standard in Ubuntu 18) are not detectd.
