### ISSUE TITLE
tbdsf_process_image.py fails with the Debian package

### ISSUE THREAD

**Issue by olebole** [lofar-astron/PyBDSF#134]
Since pybdsf [is now in Debian](https://tracker.debian.org/pkg/pybdsf), I am trying to implement some automated test (both during package build and with the installed package). With the recommended run in `test/tbdsf_process_image.py`, I however run into the following failure:
```
--> Tesselating image
Number of tiles for PSF variation ....... : 6
Determining PSF variation ............... : [======] 6/6
Interpolating PSF images ................ : [Thread raised exception PyArray_FromDimsAndDataAndDescr: use PyArray_NewFromDescr.
Traceback of thread is:
-------------------------
  File "/usr/lib/python3/dist-packages/bdsf/multi_proc.py", line 54, in worker
    result = f(val)
  File "/usr/lib/python3/dist-packages/bdsf/functions.py", line 2059, in eval_func_tuple
    return f_args[0](*f_args[1:])
  File "/usr/lib/python3/dist-packages/bdsf/psf_vary.py", line 1000, in interp_prop
    prop_int = rgrid.rgrd(prop)
  File "/usr/lib/python3/dist-packages/bdsf/nat/__init__.py", line 643, in rgrd
    t = Natgrid.rgrdPrimary(self, dataIn, aspectSlope)
  File "/usr/lib/python3/dist-packages/bdsf/nat/__init__.py", line 699, in rgrdPrimary
    dataOut, ier = natgridmodule.natgridd(self.nxi, self.xi, self.yi, dataIn, self.nxo, self.nyo, self.xo, self.yo)
-------------------------
Thread raised exception PyArray_FromDimsAndDataAndDescr: use PyArray_NewFromDescr.
Thread raised exception PyArray_FromDimsAndDataAndDescr: use PyArray_NewFromDescr.
Traceback of thread is:
Traceback of thread is:
-------------------------
-------------------------
  File "/usr/lib/python3/dist-packages/bdsf/multi_proc.py", line 54, in worker
    result = f(val)
  File "/usr/lib/python3/dist-packages/bdsf/functions.py", line 2059, in eval_func_tuple
    return f_args[0](*f_args[1:])
  File "/usr/lib/python3/dist-packages/bdsf/psf_vary.py", line 1000, in interp_prop
    prop_int = rgrid.rgrd(prop)
  File "/usr/lib/python3/dist-packages/bdsf/nat/__init__.py", line 643, in rgrd
    t = Natgrid.rgrdPrimary(self, dataIn, aspectSlope)
  File "/usr/lib/python3/dist-packages/bdsf/nat/__init__.py", line 699, in rgrdPrimary
    dataOut, ier = natgridmodule.natgridd(self.nxi, self.xi, self.yi, dataIn, self.nxo, self.nyo, self.xo, self.yo)
-------------------------
  File "/usr/lib/python3/dist-packages/bdsf/multi_proc.py", line 54, in worker
    result = f(val)
  File "/usr/lib/python3/dist-packages/bdsf/functions.py", line 2059, in eval_func_tuple
    return f_args[0](*f_args[1:])
  File "/usr/lib/python3/dist-packages/bdsf/psf_vary.py", line 1000, in interp_prop
    prop_int = rgrid.rgrd(prop)
  File "/usr/lib/python3/dist-packages/bdsf/nat/__init__.py", line 643, in rgrd
    t = Natgrid.rgrdPrimary(self, dataIn, aspectSlope)
  File "/usr/lib/python3/dist-packages/bdsf/nat/__init__.py", line 699, in rgrdPrimary
    dataOut, ier = natgridmodule.natgridd(self.nxi, self.xi, self.yi, dataIn, self.nxo, self.nyo, self.xo, self.yo)
-------------------------
ERROR: PyArray_FromDimsAndDataAndDescr: use PyArray_NewFromDescr.
Traceback (most recent call last):
  File "tbdsf_process_image.py", line 5, in <module>
    img = bdsf.process_image('tbdsf_process_image.in')
  File "/usr/lib/python3/dist-packages/bdsf/__init__.py", line 253, in process_image
    img.process(**kwargs)
  File "/usr/lib/python3/dist-packages/bdsf/image.py", line 135, in process
    success = interface.process(self, **kwargs)
  File "/usr/lib/python3/dist-packages/bdsf/interface.py", line 62, in process
    _run_op_list(img, op_chain)
  File "/usr/lib/python3/dist-packages/bdsf/__init__.py", line 152, in _run_op_list
    op(img)
  File "/usr/lib/python3/dist-packages/bdsf/psf_vary.py", line 276, in __call__
    map_list = mp.parallel_map(func.eval_func_tuple,
  File "/usr/lib/python3/dist-packages/bdsf/multi_proc.py", line 223, in parallel_map
    results = run_tasks(procs, err_q, out_q, len(sequence))
  File "/usr/lib/python3/dist-packages/bdsf/multi_proc.py", line 114, in run_tasks
    raise err_q.get()
NotImplementedError: PyArray_FromDimsAndDataAndDescr: use PyArray_NewFromDescr.
```
System info:
 * upcoming Debian 11
 * Python 3.8
 * numpy 1.18.4

The created log file is attached: [tbdsf_process_image.in_fits.pybdsf.log](https://github.com/lofar-astron/PyBDSF/files/4908256/tbdsf_process_image.in_fits.pybdsf.log.txt)

I would guess this is the deprecation in [numpy 1.18](https://numpy.org/devdocs/release/1.18.0-notes.html), just with a wrong error test: the code indeed contains some calls to `PyArray_FromDims()`, which the Numpy notes mark as "expired deprecation", f.e. https://github.com/lofar-astron/PyBDSF/blob/c46c72b3fed3cff017dcc827527f9bee06429ce7/src/c%2B%2B/num_util/num_util.cpp#L193-L195

**Comment by gmloose** [comment]
Is this still an issue, or can I close this ticket?

**Comment by olebole** [comment]
This seems to work now; I just get one warning:
```
[…]
--> Using adaptive scaling of rms_box
/usr/lib/python3/dist-packages/numpy/core/fromnumeric.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  result = getattr(asarray(obj), method)(*args, **kwds)
Derived rms_box (box size, step size) ... : (9, 3) pixels (small scale)
Derived rms_box (box size, step size) ... : (12, 4) pixels (large scale)
--> Variation in rms image not significant
[…]
```

BTW, would it be possible to rewrite the tests to use pytest? This would streamline their regular use significantly.
