### ISSUE TITLE
AttributeError: get_data_files_without_manifest when installing PyBDSF via git from master 

### ISSUE THREAD

**Issue by gabicca** [lofar-astron/PyBDSF#164]
The following error started to occur today. After googling a bit, I found this issue opened for setuptools: https://github.com/pypa/setuptools/issues/2849

Looks like people are fixing this in their own packages (see linked PRs). Could someone please take a look?

Thanks in advance!

```
Collecting bdsf@ git+https://github.com/lofar-astron/PyBDSF.git@master
  Cloning https://github.com/lofar-astron/PyBDSF.git (to revision master) to /tmp/pip-install-dxvz7gx8/bdsf_0bcdfe0f39bc4f9f91e64a8e41762409
  Running command git clone -q https://github.com/lofar-astron/PyBDSF.git /tmp/pip-install-dxvz7gx8/bdsf_0bcdfe0f39bc4f9f91e64a8e41762409
  Resolved https://github.com/lofar-astron/PyBDSF.git to commit 380ea5f2adea122bbc081658a7105f891345d799
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
 ...
  writing manifest file 'bdsf.egg-info/SOURCES.txt'
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 117, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-sbqnuwl8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-sbqnuwl8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-sbqnuwl8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 267, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-sbqnuwl8/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 282, in <module>
      main()
    File "setup.py", line 248, in main
      setup(
    File "/tmp/pip-build-env-sbqnuwl8/overlay/lib/python3.9/site-packages/numpy/distutils/core.py", line 169, in setup
      return old_setup(**new_attr)
    File "/tmp/pip-build-env-sbqnuwl8/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 159, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-sbqnuwl8/overlay/lib/python3.9/site-packages/numpy/distutils/command/egg_info.py", line 25, in run
      _egg_info.run(self)
    File "/tmp/pip-build-env-sbqnuwl8/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 299, in run
      self.find_sources()
    File "/tmp/pip-build-env-sbqnuwl8/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 306, in find_sources
      mm.run()
    File "/tmp/pip-build-env-sbqnuwl8/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 541, in run
      self.add_defaults()
    File "/tmp/pip-build-env-sbqnuwl8/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 578, in add_defaults
      sdist.add_defaults(self)
    File "/usr/local/lib/python3.9/distutils/command/sdist.py", line 226, in add_defaults
      self._add_defaults_python()
    File "/tmp/pip-build-env-sbqnuwl8/overlay/lib/python3.9/site-packages/setuptools/command/sdist.py", line 113, in _add_defaults_python
      self._add_data_files(self._safe_data_files(build_py))
    File "/tmp/pip-build-env-sbqnuwl8/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 621, in _safe_data_files
      return build_py.get_data_files_without_manifest()
    File "/usr/local/lib/python3.9/distutils/cmd.py", line 103, in __getattr__
      raise AttributeError(attr)
  AttributeError: get_data_files_without_manifest
```

**Comment by gabicca** [comment]
Looks like this was fixed at the setuptools level and the error no longer occurs. So I'll close this Issue.
