### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils.msvccompiler'

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/PyBDSF#179]
When trying to compile Singularity recipe from @mhardcastle https://github.com/mhardcastle/ddf-pipeline/blob/master/ddf-py3.singularity Im getting:
```
+ pip3 install git+https://github.com/lofar-astron/PyBDSF.git
Collecting git+https://github.com/lofar-astron/PyBDSF.git
  Cloning https://github.com/lofar-astron/PyBDSF.git to /tmp/pip-req-build-gnne44vu
  Running command git clone -q https://github.com/lofar-astron/PyBDSF.git /tmp/pip-req-build-gnne44vu
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpvwdy294r_in_process.py get_requires_for_build_wheel /tmp/tmpw8o6dmns
       cwd: /tmp/pip-req-build-gnne44vu
  Complete output (23 lines):
  Traceback (most recent call last):
    File "/tmp/tmpvwdy294r_in_process.py", line 280, in <module>
      main()
    File "/tmp/tmpvwdy294r_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmpvwdy294r_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-x2nwds5i/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 337, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-x2nwds5i/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 319, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-x2nwds5i/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 474, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-x2nwds5i/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 334, in run_setup
      exec(code, locals())
    File "<string>", line 7, in <module>
    File "/usr/local/lib/python3.9/dist-packages/numpy/distutils/core.py", line 24, in <module>
      from numpy.distutils.command import config, config_compiler, \
    File "/usr/local/lib/python3.9/dist-packages/numpy/distutils/command/config.py", line 19, in <module>
      from numpy.distutils.mingw32ccompiler import generate_manifest
    File "/usr/local/lib/python3.9/dist-packages/numpy/distutils/mingw32ccompiler.py", line 28, in <module>
      from distutils.msvccompiler import get_build_version as get_build_msvc_version
  ModuleNotFoundError: No module named 'distutils.msvccompiler'
```
I reverted recent commit (which removed `pyfits`) and put `pyfits` back in - and Im still getting this error.
This is probably because of `distutils` was updated 3 days ago:
https://github.com/RKrahl/distutils-pytest/blob/master/CHANGES.rst#incompatible-changes

**Comment by mhardcastle** [comment]
I think this is fixed now and can be closed.
