### ISSUE TITLE
Python 3.12 compatibility

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/PyBDSF#214]
Just reporting:

```
Collecting bdsf (from rapthor==1.2.dev11+g18ecc80)
  Downloading bdsf-1.10.3.tar.gz (360 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 360.2/360.2 kB 3.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/home/akurek/miniconda3/envs/rapthor-py12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/akurek/miniconda3/envs/rapthor-py12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/akurek/miniconda3/envs/rapthor-py12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/home/akurek/miniconda3/envs/rapthor-py12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/akurek/miniconda3/envs/rapthor-py12/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-u_vd2jsh/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-u_vd2jsh/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-u_vd2jsh/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2191, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

**Comment by gmloose** [comment]
Unresolved. I'll put it higher on my to-do list.

**Comment by gmloose** [comment]
I'm working on a solution. The problem is already partly fixed in branch fix-python3.12-build. The build completes successfully, however the binary wheel is broken, because the shared module `_pytesselate` that is built with `f2py` misses symbols.

The only thing that has changed between Python 3.11 and Python 3.12 is that NumPy dropped `distutils` (because it's now obsolete) and now uses `meson` for building. So, I see at least three possible options where the problem may lie:

1. The `CMakeLists.txt` file for `PyBDSF` is incomplete and just happened to work with `distutils`.
2. There's a bug in `numpy.f2py`, e.g., it doesn't pass all the required options to `meson`.
3. There's a bug in `meson`.

**Comment by gmloose** [comment]
Fixed by https://github.com/lofar-astron/PyBDSF/pull/216.
