### ISSUE TITLE
Slice indexes must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by tammojan** [lofar-astron/PyBDSF#24]
The following occurs during testing `tbdsm_process_image` on the new CEP3 (CentOS7):
```
135: --> Estimating PSF variations
135: Traceback (most recent call last):
135:   File "tbdsm_process_image.py", line 5, in <module>
Calculating polarisation properties ....  : [==========================================] 42/42
135:     img = bdsm.process_image('tbdsm_process_image.in')
135:   File "/opt/cep/pybdsf/current/bdsf-1.8.9-py2.7-linux-x86_64.egg/bdsf/__init__.py", line 243, in process_image
135:     img.process(**kwargs)
135:   File "/opt/cep/pybdsf/current/bdsf-1.8.9-py2.7-linux-x86_64.egg/bdsf/image.py", line 126, in process
135:     success = interface.process(self, **kwargs)
135:   File "/opt/cep/pybdsf/current/bdsf-1.8.9-py2.7-linux-x86_64.egg/bdsf/interface.py", line 53, in process
135:     _run_op_list(img, op_chain)
135:   File "/opt/cep/pybdsf/current/bdsf-1.8.9-py2.7-linux-x86_64.egg/bdsf/__init__.py", line 149, in _run_op_list
135:     op(img)
135:   File "/opt/cep/pybdsf/current/bdsf-1.8.9-py2.7-linux-x86_64.egg/bdsf/psf_vary.py", line 134, in __call__
135:     flag_unresolved = self.get_unresolved(g_gauls, img.beam, nsig, kappa2, over, img.psf_high_snr, plot)
135:   File "/opt/cep/pybdsf/current/bdsf-1.8.9-py2.7-linux-x86_64.egg/bdsf/psf_vary.py", line 505, in get_unresolved
135:     (s_c,s_dm) = self.fit_bins_func(xarr,yarr,over,ptpbin,nbin,ptplastbin,nsig)  # size_ksclip_wenss in fBDSM
135:   File "/opt/cep/pybdsf/current/bdsf-1.8.9-py2.7-linux-x86_64.egg/bdsf/psf_vary.py", line 446, in fit_bins_func
135:     (xval,meany,stdy,medy)=self.bin_and_stats_ny(x,y,over,ptpbin,nbin,ptplastbin,nsig)
135:   File "/opt/cep/pybdsf/current/bdsf-1.8.9-py2.7-linux-x86_64.egg/bdsf/psf_vary.py", line 405, in bin_and_stats_ny
135:     x1=x[lb:ub+1]; y1=y[lb:ub+1]
135: TypeError: slice indices must be integers or None or have an __index__ method
135: FAIL (execution failure): tbdsm_process_image
1/1 Test #135: tbdsm_process_image ..............***Failed   15.72 sec
```

**Comment by tammojan** [comment]
This was fixed in  32bc893
