### ISSUE TITLE
Interactive shell does not work on CentOS 7

### ISSUE THREAD

**Issue by tammojan** [lofar-astron/PyBDSF#28]
Trying to install release 1.8.10 on CentOS 7 (in fact, the new CEP3), we run into an issue opening the `bdsf` shell:
```
bash-4.2$ pybdsf
/usr/lib/python2.7/site-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
Traceback (most recent call last):
  File "/opt/cep/pybdsf/PyBDSF-1.8.10/bin/pybdsf", line 4, in <module>
    __import__('pkg_resources').run_script('bdsf==1.8.10', 'pybdsf')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/shared/cep/pybdsf/PyBDSF-1.8.10/lib64/python2.7/site-packages/bdsf-1.8.10-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pybdsf", line 715, in <module>
    user_ns=locals())
  File "/usr/lib/python2.7/site-packages/IPython/terminal/embed.py", line 158, in __init__
    super(InteractiveShellEmbed,self).__init__(**kw)
  File "/usr/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 431, in __init__
    super(TerminalInteractiveShell, self).__init__(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 446, in __init__
    super(InteractiveShell, self).__init__(**kwargs)
  File "/usr/lib/python2.7/site-packages/traitlets/config/configurable.py", line 84, in __init__
    self.config = config
  File "/usr/lib/python2.7/site-packages/traitlets/traitlets.py", line 585, in __set__
    self.set(obj, value)
  File "/usr/lib/python2.7/site-packages/traitlets/traitlets.py", line 559, in set
    new_value = self._validate(obj, value)
  File "/usr/lib/python2.7/site-packages/traitlets/traitlets.py", line 591, in _validate
    value = self.validate(obj, value)
  File "/usr/lib/python2.7/site-packages/traitlets/traitlets.py", line 1677, in validate
    self.error(obj, value)
  File "/usr/lib/python2.7/site-packages/traitlets/traitlets.py", line 1524, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'config' trait of an InteractiveShellEmbed instance must be a Config, but a value of class 'IPython.config.loader.Config' (i.e. {'PromptManager': {'in_template': 'BDSF [\\#]: '}, 'InteractiveShellEmbed': {'autocall': 2}}) was specified.
```

**Comment by darafferty** [comment]
I added support for the traitlets config. @tammojan, can you try it on CEP3?

**Comment by tammojan** [comment]
Yup, works on CEP3. Thanks for the quick action!
