### ISSUE TITLE
Undefined symbol on Ubuntu 18.04 when importing bdsf

### ISSUE THREAD

**Issue by tjuerges** [lofar-astron/PyBDSF#58]
Set-up:

- Ubuntu 18.04 (bionic) in a Docker image with current updates
- libboost-python1.65-dev package is installed (pulled in by libboost-all-dev)

Compilation of v1.8.14 (or master) is fine.  But when Python tries to import the module, then this happens:
`Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bdsf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/pybdsf/lib/python2.7/site-packages/bdsf-1.8.14-py2.7-linux-x86_64.egg/bdsf/__init__.py", line 19, in <module>
    from collapse import Op_collapse
  File "/opt/pybdsf/lib/python2.7/site-packages/bdsf-1.8.14-py2.7-linux-x86_64.egg/bdsf/collapse.py", line 10, in <module>
    import _cbdsm
ImportError: /opt/pybdsf/lib/python2.7/site-packages/bdsf-1.8.14-py2.7-linux-x86_64.egg/bdsf/_cbdsm.so: undefined symbol: _ZN5boost6python5numpy6detail13get_int_dtypeILi64ELb0EEENS1_5dtypeEv
>>> `

When I purge libboost-python1.65-dev from the system and install libboost-python1.62 & libboost-python1.62-dev instead, the compilation is again fine.  But this time the import works nicely:

```
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bdsf
/usr/local/lib/python2.7/dist-packages/pyfits/__init__.py:22: PyFITSDeprecationWarning: PyFITS is deprecated, please use astropy.io.fits
  PyFITSDeprecationWarning)  # noqa
>>>
```

I had a look at the code and found in _src/c++/num_util/num_util.cpp_ this:
```
//Return a clone of this array with a new type
pyndarray astype(pyndarray arr, PyArray_TYPES t){
  #if BOOST_VERSION < 106500
    return (pyndarray) arr.astype(type2char(t));
  #else
    return (pyndarray) arr.astype(type2dtype(type2char(t)));
  #endif
}
```
and
```
#if BOOST_VERSION >= 106500
boost::python::numpy::dtype type2dtype(char t){

  switch(t) {
    case 'B':
      return boost::python::numpy::dtype::get_builtin<unsigned char>();
    case 'b':
      return boost::python::numpy::dtype::get_builtin<signed char>();
    case 'h':
      return boost::python::numpy::dtype::get_builtin<short>();
    case 'i':
      return boost::python::numpy::dtype::get_builtin<int>();
    case 'l':
      return boost::python::numpy::dtype::get_builtin<long int>();
    case 'f':
      return boost::python::numpy::dtype::get_builtin<float>();
    case 'd':
      return boost::python::numpy::dtype::get_builtin<double>();
    case 'F':
      return boost::python::numpy::dtype::get_builtin<std::complex<float>>();
    case 'D':
      return boost::python::numpy::dtype::get_builtin<std::complex<double>>();
    default:
      std::cout << "Invalid character code!" << std::endl;
      break;
  }
}
#endif
```
Using Boost < 1.65 will disable that code and result in a working module.

**Comment by gijzelaerr** [comment]
i'm experiencing the same issue.

**Comment by gijzelaerr** [comment]
looks like those numpy boost symbols are in a seperate library, which are in the libboost-numpy1.65-dev package.

`objdump -TC /usr/lib/x86_64-linux-gnu/libboost_numpy-py27.so | grep get_int_dtype`

**Comment by gijzelaerr** [comment]
manually adding boost-numpy to the `setup.py` file seems to solve the problem:
```
diff --git a/setup.py b/setup.py
index 0f98bc4..7732b1a 100755
--- a/setup.py
+++ b/setup.py
@@ -118,7 +118,7 @@ def main():
                  "src/c++/cbdsm_main.cc",
                  "src/c++/stat.cc",
                  "src/c++/num_util/num_util.cpp"],
-         libraries=['minpack', 'port3', 'gfortran', boost_python],
+         libraries=['minpack', 'port3', 'gfortran', boost_python, 'boost_numpy-py27'],
          include_dirs=["src/c++"],
          library_dirs=[join(srcpath,"minpack"), join(srcpath,"port3")]
          ))
```

**Comment by MaxNoe** [comment]
Would you open a PR? We are experiencing the same problem

**Comment by MaxNoe** [comment]
boost_numpy seems to be deprecated in favor of `boost::python::numpy` starting with boost 1.63. How to fix this?

**Comment by gijzelaerr** [comment]
i just pushed a fixed version to KERN-4 http://kernsuite.info

**Comment by MaxNoe** [comment]
I'm not really understanding how a link to a symbol only defined in `libboost_numpy` lands in the built binary. If I understood the latest commits correctly, it is using `libboost-python` which nowadays includes support for numpy and not `libboost_numpy`.

So why is linking against `libboost_numpy` necessary?

**Comment by MaxNoe** [comment]
> i just pushed a fixed version to KERN-4 http://kernsuite.info

Why did you not try to fix it here?

**Comment by MaxNoe** [comment]
from https://launchpad.net/ubuntu/+source/boost-defaults
> libboost-numpy-dev: Boost.Python NumPy extensions development files 

So this is actually `boost_python/numpy` and not the deprecated `boost_numpy`

**Comment by MaxNoe** [comment]
Should be fixed now, due to #66
