### ISSUE TITLE
Setup failed: no attribute 'extra_f77_compile_args'

### ISSUE THREAD

**Issue by alxames** [lofar-astron/PyBDSF#7]
I'm trying to install PyBDSF 1.8.8 on CentOS 7.2, but the command
```
python setup.py build
```
fails, likely because CentOS' numpy 1.7.1-11.el7 is too old:
```
[...]
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext
building 'bdsf._pytesselate' extension
Traceback (most recent call last):
  File "setup.py", line 101, in <module>
    setup(**meta)
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/core.py", line 186, in setup
    return old_setup(**new_attr)
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/command/build.py", line 37, in run
    old_build.run(self)
  File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/command/build_ext.py", line 232, in run
    self.build_extensions()
  File "/usr/lib64/python2.7/distutils/command/build_ext.py", line 448, in build_extensions
    self.build_extension(ext)
  File "/usr/lib64/python2.7/site-packages/numpy/distutils/command/build_ext.py", line 303, in build_extension
    fcompiler.extra_f77_compile_args = ext.extra_f77_compile_args or []
AttributeError: Extension instance has no attribute 'extra_f77_compile_args'
```

Could you resolve this error (preferably for me), or else enforce minimum versions?

**Comment by alxames** [comment]
Thanks a lot!
