### ISSUE TITLE
Crash in Gaussian fitting

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/PyBDSF#96]
Normal-looking LOFAR image crashes with this error:

```
--> Wavelet scale #4
--> Calculating background rms and mean images
Using user-specified rms_box ............ : (165, 55) pixels
--> Using 2D map for background rms
--> Using constant background mean
Min/max values of background rms map .... : (0.00001, 0.00022) Jy/beam
Value of background mean ................ : 0.0 Jy/beam
Number of islands found ................. : 31
Fitting islands with Gaussians .......... : [==============================/soft/python/lib64/python2.7/site-packages/numpy/core/fromnumeric.py:2909: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
Thread raised exception cannot convert float NaN to integer
Traceback of thread is:
-------------------------
  File "/home/mjh/.local/lib/python2.7/site-packages/bdsf-1.9.0-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 54, in worker
    result = f(val)
  File "/home/mjh/.local/lib/python2.7/site-packages/bdsf-1.9.0-py2.7-linux-x86_64.egg/bdsf/functions.py", line 2058, in eval_func_tuple
    return f_args[0](*f_args[1:])
  File "/home/mjh/.local/lib/python2.7/site-packages/bdsf-1.9.0-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 247, in process_island
    gaul, fgaul = self.fit_island(isl, opts, img)
  File "/home/mjh/.local/lib/python2.7/site-packages/bdsf-1.9.0-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 311, in fit_island
    gaul = self.inigaus_nobeam(isl, thr0, beam, img)
  File "/home/mjh/.local/lib/python2.7/site-packages/bdsf-1.9.0-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 586, in inigaus_nobeam
    max(0,int(ym[i+1]-avsize/2)):min(im.shape[1],int(ym[i+1]+avsize/2))] = True
-------------------------
Traceback (most recent call last):
  File "/home/mjh/pipeline-master/ddf-pipeline/scripts/quality_pipeline.py", line 175, in <module>
    sfind_image(o['catprefix'],o['pbimage'],o['nonpbimage'],o['sfind_pixel_fraction'])
  File "/home/mjh/pipeline-master/ddf-pipeline/scripts/quality_pipeline.py", line 99, in sfind_image
    img = bdsm.process_image(pbimage, detection_image=nonpbimage, thresh_isl=4.0, thresh_pix=5.0, rms_box=(160,50), rms_map=True, mean_map='zero', ini_method='intensity', adaptive_rms_box=True, adaptive_thresh=150, rms_box_bright=(60,15), group_by_isl=False, group_tol=10.0,output_opts=True, output_all=True, atrous_do=True,atrous_jmax=4, flagging_opts=True, flag_maxsize_fwhm=0.5,advanced_opts=True, blank_limit=None,**kwargs)
  File "/home/mjh/.local/lib/python2.7/site-packages/bdsf-1.9.0-py2.7-linux-x86_64.egg/bdsf/__init__.py", line 246, in process_image
    img.process(**kwargs)
  File "/home/mjh/.local/lib/python2.7/site-packages/bdsf-1.9.0-py2.7-linux-x86_64.egg/bdsf/image.py", line 135, in process
    success = interface.process(self, **kwargs)
  File "/home/mjh/.local/lib/python2.7/site-packages/bdsf-1.9.0-py2.7-linux-x86_64.egg/bdsf/interface.py", line 62, in process
    _run_op_list(img, op_chain)
  File "/home/mjh/.local/lib/python2.7/site-packages/bdsf-1.9.0-py2.7-linux-x86_64.egg/bdsf/__init__.py", line 152, in _run_op_list
    op(img)
  File "/home/mjh/.local/lib/python2.7/site-packages/bdsf-1.9.0-py2.7-linux-x86_64.egg/bdsf/wavelet_atrous.py", line 180, in __call__
    op(wimg)
  File "/home/mjh/.local/lib/python2.7/site-packages/bdsf-1.9.0-py2.7-linux-x86_64.egg/bdsf/gausfit.py", line 99, in __call__
    bar=bar, weights=weights)
  File "/home/mjh/.local/lib/python2.7/site-packages/bdsf-1.9.0-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 223, in parallel_map
    results = run_tasks(procs, err_q, out_q, len(sequence))
  File "/home/mjh/.local/lib/python2.7/site-packages/bdsf-1.9.0-py2.7-linux-x86_64.egg/bdsf/multi_proc.py", line 114, in run_tasks
    raise err_q.get()
ValueError: cannot convert float NaN to integer
```

I'm guessing this is connected to the 'mean of empty slice' issue in the sense that numpy computes some NaN value which is then used to compute the size of a window. Really in this situation I guess the only thing to do is bale out of fitting to the island altogether...

Don't really have time to debug this right now but I can look at some later stage if it's not obvious to anyone else.

**Comment by mhardcastle** [comment]
OK, I just shoved some print statements in there during a telecon... this looks like a simple logic error in `inigaus_nobeam` around line 577 onwards. If the list `compact` is all false, then `avgsize` will end up as `NaN`, as the mean of an empty array, and then be used in calculations in the next stage of the code. Easy to check for this, but I don't really know what `avgsize` should be set to in this case -- any ideas @darafferty ?

**Comment by darafferty** [comment]
Hmm, to be honest, I'm not really sure (this is stuff Niruj coded long ago). Perhaps adjust the definition of `compact` until at least one of its elements is True? That is, iteratively increase the value that is now `3.0` in `if dist < max(3.0, meandist/4.0)` until it's true at least once. I suspect that the value of 3 is a bit arbitrary and might need to be tuned occasionally, but that's really just a guess.

**Comment by mhardcastle** [comment]
Sounds worth trying. I'll give it a go. (The good news is that this is such a rare error that almost any workround is probably good enough -- first time we've triggered it in over 500 similar fields.)
